title: Mazama
description: Partage d'exp√©riences, POCs et tutoriels DevOps - Docker, Kubernetes, CI/CD
theme: just-the-docs

url: https://mazama923.github.io

aux_links:
  GitHub: https://github.com/mazama923

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "/blog/page:num/"

nav_enabled: true
nav_sort: case_insensitive

callouts:
  note:
    title: Note
    color: purple

enable_copy_code_button: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
