title: Mazama
description: Partage d'exp√©riences, POCs et tutoriels DevOps - Docker, Kubernetes, CI/CD
theme: just-the-docs

url: https://mazama923.github.io

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  GitHub: https://github.com/mazama923

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "/blog/page:num/"

nav_enabled: true
nav_sort: case_insensitive

callouts:
  note:
    title: Note
    color: purple

enable_copy_code_button: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Google Analytics Tracking
ga_tracking: G-PF6WHHLCHD
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
